<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "typo3themeskeleton"
 *
 * Auto generated by Extension Builder 2017-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['typo3themeskeleton'] = [
    'title' => 'GroundStack Theme Skeleton',
    'description' => 'Distribution theme skeleton: Anpassbar im Backend im Konstanten Editor.',
    'category' => 'distribution',
    'author' => 'Christian Hackl',
    'author_email' => 'chackl@hauer-heinrich.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.9.99',
            'fluid_styled_content' => '8.7.0-9.0.0',
            'gridelements' => '8.0.0-8.9.9',
            'news' => '7.0.0-7.9.9',
            'tt_address' => '4.0.0-4.9.9',
            'powermail' => '6.0.0-6.9.9'
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
    'autoload' => [
        'psr-4' => [
            'GroundStack\\Typo3ThemeSkeleton\\' => 'Classes'
        ],
    ],
];
