<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "hhthemekroeswang"
 *
 * Auto generated by Extension Builder 2017-02-24
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF['hhthemekroeswang'] = [
    'title' => 'Kroeswang',
    'description' => 'Distribution Kroeswang: Anpassbar im Backend im Konstanten Editor.',
    'category' => 'distribution',
    'author' => 'Christian Hackl / Sebastian Pieczona',
    'author_email' => 'web@hauer-heinrich.de',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.9.99',
            'fluid_styled_content' => '8.7.0-9.0.0',
            'gridelements' => '8.0.0-8.9.9',
            'news' => '7.0.0-7.9.9',
            'tt_address' => '3.2.3-3.9.9',
            'cyz_address' => '0.5.0-0.9.9',
            'powermail' => '6.0.0-6.9.9',
            'realurl' => '2.4.0-2.99.99'
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
    'autoload' => [
        'psr-4' => [
            'HauerHeinrich\\Hhthemekroeswang\\' => 'Classes'
        ],
    ],
];
